filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php: {  }
build:
    environment:
        php: '7.1'
    tests:
        override:
            -
                command: composer test
                coverage:
                    file: build/coverage.xml
                    format: php-clover
