filter:
    excluded_paths:
        - 'tests/'
    dependency_paths:
        - 'vendor/'
checks:
    php: true
coding_style:
    php: {  }
build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
        testing:
            environment:
                php: '7.1'
            tests:
                override:
                    -
                        command: composer test
                        coverage:
                            file: build/phpunit/clover.xml
                            format: php-clover
