on: push

jobs:
  test:
    name: Run tests in PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    container: 1maa/php-dev:${{ matrix.php-version }}
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.0", "8.1", "8.2"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install dependencies
        run: composer install
      - name: Run Linter
        run: vendor/bin/php-cs-fixer fix -v --dry-run
      - name: Execute test suite
        run: composer test
