on: push

jobs:
  test:
    name: Run tests in PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    container: 1maa/php-dev:${{ matrix.php-version }}
    strategy:
      fail-fast: false
      matrix:
        php-version: ["7.3", "7.4", "8.0", "8.1"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install dependencies
        run: composer install
      - name: Execute test suite
        run: composer test
      - name: Send coverage to Scrutinizer CI
        if: ${{ always() && matrix.php-version == '8.1' }}
        run: |
          git config --global --add safe.directory /__w/JsonRpc/JsonRpc
          php vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage.xml
